import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import styled from "styled-components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Body = styled.body`
  height: 100%;
`

const Html = styled.html`
  height: 100%;
`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <Html lang="en">
        <Body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </Body>
      </Html>
    </ConvexAuthNextjsServerProvider>
  );
}
